---
layout: page
title: "데이터 과학 - 시각화"
subtitle: "코로나19 사망자와 경제성장율"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "코로나19", "Covid-19", "사망자", "Mortality", "경제성장율"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_viz.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: bluee
editor_options: 
  chunk_output_type: console
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# 연령별 코로나 사망자 [^youtube-mortality] {#mortality-by-age}

[^youtube-mortality]: [Emmanuel Olamijuwon (Estwatini R User Group Organizer), "COVe[R]AGE-DB: Uncovering the demographic dynamics of COVID19 cases and deaths using R.", "Why R? Foundation"](https://www.youtube.com/watch?v=c7QJ2Gc2dTI)

[COVerAGE-DB: A database of COVID-19 cases and deaths by age](https://osf.io/mpwjq/) 데이터가 공개되어 코로나19로 인한 사망에 대한 많은 정보를 얻을 수 있다.


# R 팩키지 {#r-pkg}

[COVerAGE-DB - R 팩키지](https://github.com/timriffe/covid_age)가 있어 바로 데이터를 분석할 수 있게 실시간으로 정보를 제공하고 있다.

```{r r-pkg-coverage-db}
library(tidyverse)
# remotes::install_github("eshom/covid-age-data")
library(covidAgeData)
library(lubridate)

# inputDB <- download_covid("inputDB", progress = FALSE)
inputDB <-  read_csv("inputDB.zip",
                     skip = 1,
                     col_types = "cccccciccdc")

korea_tbl <- subset_covid(inputDB, Country = "South Korea", Region = "All") %>% 
  # 변수명과 자료형 작업
  as_tibble() %>% 
  janitor::clean_names(.) %>% 
  mutate(date = dmy(date)) %>%
  # 분석에 필수 변수만 추리는 작업
  select(date, sex, age, measure, value) %>% 
  # 변수 가독성 향상 작업
  mutate(sex = case_when(sex == 'b' ~ "남녀",
                         sex == 'f' ~ "여성",
                         sex == 'm' ~ "남성"),
         age = case_when(age == '0'  ~ "00~09",
                         age == '10' ~ "10~19",
                         age == '20' ~ "20~29",
                         age == '30' ~ "30~39",
                         age == '40' ~ "40~49",
                         age == '50' ~ "50~59",
                         age == '60' ~ "60~69",
                         age == '70' ~ "70~79",
                         age == '80' ~ "80~"),
         measure = ifelse(measure == "Cases", "확진", "사망")) %>% 
  # 결측값 제거  
  filter(!is.na(age))

  
korea_tbl
```


# 한국 {#covid-korea}

앞선 데이터 전처리 이후 대한민국 코로나 19 확진 및 사망 남녀 연령별로 살펴보기 위해 데이터를 확인한다. 

```{r covid-korea}
korea_tbl %>%
  skimr::skim(.)
```


# 탐색적 데이터분석 {#covid-korea-eda}

## 연령대별 누적 사망자

```{r covid-korea-time-series}
library(timetk)

korea_tbl %>%
  filter(date >= ymd("2020-07-01")) %>% 
  filter(measure == "사망") %>% 
  group_by(age) %>% 
  plot_time_series(date, value, 
                   .facet_ncol   = 3, 
                   .interactive  = FALSE,
                   .facet_scales = "free",
                   .line_alpha   = 1,
                   .smooth       = FALSE, 
                   .smooth_size  = 0.5,
                   .smooth_alpha = 0.3) +
  scale_y_continuous(labels = scales::comma_format(), limits = c(0,1200)) +
  scale_x_date(date_labels = "%y-%m") +
  theme_bw(base_family = "NanumGothic") +
  labs(title = "연령대별 누적사망자")
```

## 연령대별 누적 확진자

```{r covid-korea-time-series-confirmed}
korea_tbl %>%
  filter(date >= ymd("2020-07-01")) %>% 
  filter(measure == "확진") %>% 
  group_by(age) %>% 
  plot_time_series(date, value, 
                   .facet_ncol   = 3, 
                   .interactive  = FALSE,
                   .facet_scales = "free",
                   .line_alpha   = 1,
                   .smooth       = FALSE, 
                   .smooth_size  = 0.5,
                   .smooth_alpha = 0.3) +
  scale_y_continuous(labels = scales::comma_format(), limits = c(0, 20000)) +
  scale_x_date(date_labels = "%y-%m") +
  theme_bw(base_family = "NanumGothic") +
  labs(title = "연령대별 누적 확진자")
```
